name: Release
on:
  - push

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: make release
      - uses: actions/upload-artifact@v3
        with:
          path: ./*.zip
  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: make release
      - uses: actions/upload-artifact@v3
        with:
          path: ./*.tar.gz
  build-linux-musl:
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:jdk-11.0.15_10-alpine-slim
    steps:
      - uses: actions/checkout@v3
      - run: apk add linux-headers make g++ && make release
      - uses: actions/upload-artifact@v3
        with:
          path: ./*.tar.gz
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: addnab/docker-run-action@v3
      #   with:
      #     image: openjdk:11.0.15-jdk-buster
      #     options: -v ${{ github.workspace }}:/work --platform linux/arm64
      #     run: apt update && apt install g++ make -y && cd /work && make release
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:2022-01-28
          copy_artifact_path: "./*.tar.gz"
          commands: |
            sudo apt update && sudo apt install g++ make openjdk-11-dbg -y && cd /work && make release
      # - run: >
      #     docker run --entrypoint bash --platform linux/arm64 -v $(pwd):/work openjdk:11.0.15-jdk-buster -c "apt update && apt install g++ make -y && cd /work && make release"
      - uses: actions/upload-artifact@v3
        with:
          path: ./*.tar.gz
